branches:
    only:
        - master

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      sudo: required
      apt:
       packages:
        - python-tk
    - os: osx
      language: generic

install:
  - pip install --upgrade pip
  - pip install numpy==1.13.1
  - pip install cython==0.26
  - pip install scikit-learn==0.19.0
  - pip install scipy==0.19.1
  - pip install matplotlib==2.0.2
  - pip install mdtraj==1.8.0
  - sudo apt-get install python-tk
  - wget http://download.sourceforge.net/pmw/Pmw.1.3.tar.gz
  - tar -xvf Pmw.1.3.tar.gz
  - pushd ./src/Pmw && sudo python ../setup.py install

script: 
  - cd tests
  - ./test_pyMODE-TASK.sh
