branches:
    only:
        - master

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      dist: trusty
      language: python
      python: 2.7
      sudo: required
      apt:
       packages:
        - python-tk
    - os: osx
      language: generic
